require 'byebug'
require_relative '../spec/spec_helper'
require_relative 'InputData'
require_relative 'DataClients'
require_relative 'Projects'
require_relative 'DataClient_Sql'
require_relative 'shared_context'
require_relative 'DataClientServices'
require_relative 'Custom_attributes'
# require 'tiny_tds'
require 'RestServiceBase'
require 'rest-client'
require 'json'
