# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"
gem 'solid_assert'
gem 'log4r'
gem 'TestFramework', :git => 'https://github.consilio.com/QA/Browser-Framework.git'
gem 'watir'
gem 'watir-webdriver'
gem 'json'
gem 'rspec'
gem 'byebug'


# gem "rails"
